### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by rodrigopasc** [nikoferro/arkit-sticky-notes#2]
I am trying to build an experimental AR app, but I'm stuck with vertical detection.

It's so difficult to make it precise. Did you have that problem?

Thank you!

**Comment by nikoferro** [comment]
Its a bit trickier than horizontal detection for sure. And i do remember that not all the surfaces were actually accurate. The app would not perform that well when pointing at white walls where there is no difference in texture to understand that the plane is a vertical one.

The logic is all here: https://github.com/nikoferro/arkit-sticky-notes/blob/master/sticky/ViewController.swift
